#!/bin/sh -e
#DEBHELPER#
if [ "$1" = purge ]; then
	rm -f /var/log/base-config.log* 2>/dev/null || true
	rm -f /var/log/base-config.timings* 2>/dev/null || true
	
	# From base-config prior to 2.0.
	rm -f /var/log/installer.log* 2>/dev/null || true
	rm -f /var/log/installer.timings* 2>/dev/null || true
fi
