#!/bin/sh -e

. /usr/share/debconf/confmodule

ARCH=`udpkg --print-architecture`

log() {
    logger -t uda-first-message "info: $@"
}

db_settitle uda-first-message/title
db_input critical uda-first-message/first-message || [ $? -eq 30 ]
db_go

db_input critical uda-first-message/requirements || [ $? -eq 30 ]
db_go

log "Showing UDA first-message"

exit 0
