#!/bin/sh
# 

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac



. /conf/initramfs.conf

# Fixing sudo problems with netapplet
mv ${rootmnt}/usr/bin/netapplet ${rootmnt}/usr/bin/netapplet.orig

cat <<EOF > ${rootmnt}/usr/bin/netapplet
#!/bin/sh

sudo /usr/bin/netapplet.orig \$*

EOF

${rootmnt}/bin/chmod +x ${rootmnt}/usr/bin/netapplet 


# Fixing find noleaf problems with unionfs
mv ${rootmnt}/usr/bin/find ${rootmnt}/usr/bin/find.orig

cat <<EOF > ${rootmnt}/usr/bin/find
#!/bin/sh
IFS=""
/usr/bin/find.orig -L -P \$@

EOF

${rootmnt}/bin/chmod +x ${rootmnt}/usr/bin/find


# Fixing reboot command and eject process from everywhere
# Commenting out next lines to see if it is fixed with lots of
# chvt's so that it doesn't always halt
# Not commenting again
mv ${rootmnt}/sbin/reboot ${rootmnt}/sbin/reboot.orig

cat <<EOF > ${rootmnt}/sbin/reboot
#!/bin/sh

chvt 1
/sbin/reboot.orig \$@

EOF

${rootmnt}/bin/chmod +x ${rootmnt}/sbin/reboot
# Copying hacked version of halt
cp /conf/halt ${rootmnt}/sbin/halt >> /tmp/initramfs.debug 2>&1

# Changing timeout of dhclient to 30 instead of 20
sed -i "s/timeout 20/timeout 30/g" ${rootmnt}/etc/dhcp3/dhclient.conf

# Setting right permissions for every dir in which we modify files from here
# Right now, they are: /sbin, /usr/bin
chmod 755 ${rootmnt}/sbin
chmod 755 ${rootmnt}/usr/bin
chmod 755 ${rootmnt}/etc
chmod 755 ${rootmnt}/etc/dhcp3

exit 0
