#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


# Finding the first disk
DISK=$(grep '[sh]d[a-g]' /proc/partitions | while read a b c d ; do echo $d | cut -c 0-3 ; done | sort -u | head -1)
DISK='/dev/${DISK}'

# We alrady now there is just 2 partitions and
# which one is each
ROOT_PARTITION='$DISK1'
SWAP_PARTITION='$DISK2'

# Format the partitions
mkfs.ext3 $ROOT_PARTITION
mkswap $SWAP_PARTITION


# Activate the swap
swapon $SWAP_PARTITION

# Mounting main partition
mount -t ext3 $ROOT_PARTITION /mnt/

