#!/bin/sh
# Get the image, putting in the rigth place and mount it

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

SERVER=$(grep serverip /etc/config.cfg | cut -d '=' -f 2)

mkdir -p /mnt/META/
ftpget $SERVER /mnt/META/META.squashfs /cdrom/META/META.squashfs

# Just to be sure
modprobe -q squashfs
modprobe -q loop

mount -o loop -t squashfs /mnt/META/META.squashfs /root 
