#!/bin/sh

[ -z "$1" ] && echo "Usage: $0 path-to-debs" && exit 1

OUTDIR="out"
rm -rf $OUTDIR
RET=""

get_dir () {
	DIRPOOL=""
	DIRPOOL=$(dpkg --field $1 Source)
	[ -z "$DIRPOOL" ] && DIRPOOL=$(dpkg --field $1 Package)
	RET="pool/main/$(echo $DIRPOOL | cut -c 1)/$DIRPOOL"
	echo $RET
}

VAR=$1

while [ ! -z "$VAR" ]
do
	shift

	case $VAR in
	-h|h)
		echo "Shout help, maybe you are lucky today..."
		;;
	*)
		[ ! -d $VAR ] && echo "The argument is not a directory!" && exit 1

		PACKAGES=$(find $VAR | grep -e "\.deb$")


		[ -z "$PACKAGES" ] && echo "There is no packages on this directory!" && exit 1

		# Create the pool/
		for x in $PACKAGES
		do
			DESTDIR=$(get_dir $x)
			[ ! -d $OUTDIR/$DESTDIR ] && mkdir -p $OUTDIR/$DESTDIR			
			cp $x $OUTDIR/$DESTDIR	
		done
		
		# Create indices
		mkdir $OUTDIR/indices
		touch $OUTDIR/indices/override.flamenco.main 
	
		# Create the dists/
		[ -d $OUTDIR/dists/flamenco/main/binary-i386 ] || mkdir -p $OUTDIR/dists/flamenco/main/binary-i386 
		[ -d $OUTDIR/dists/flamenco/main/source ] || mkdir $OUTDIR/dists/flamenco/main/source

		apt-ftparchive -c apt_flamenco.conf generate flamenco.conf
		apt-ftparchive -c apt_flamenco.conf release $OUTDIR/dists/flamenco/ > $OUTDIR/dists/flamenco/Release
		gpg --output $OUTDIR/dists/flamenco/Release.gpg -ba $OUTDIR/dists/flamenco/Release


		# Create the .disk/
		[ ! -d $OUTDIR/.disk ] && mkdir $OUTDIR/.disk
		echo "main" > $OUTDIR/.disk/base_components
		touch $OUTDIR/.disk/base_installable
		echo "Guadalinex-2005-Flamenco" > $OUTDIR/.disk/info

		# Create the README.diskdefines
		cat >> $OUTDIR/README.diskdefines <<EOF
#define DISKNAME  Guadalinex 2005 "Flamenco" - Beta i386
#define TYPE  binary"
#define TYPEbinary  1"
#define ARCH  i386"
#define ARCHi386  1"
#define DISKNUM  1"
#define DISKNUM1  1"
#define TOTALNUM  1"
#define TOTALNUM1  1"
EOF
		# Create guadalinex-suplementos-apps
		[ ! -d $OUTDIR/guadalinex-suplementos-apps ]  && mkdir $OUTDIR/guadalinex-suplementos-apps

		# Create the iso image
		mkisofs -o guadalinex-suplementos.iso -joliet-long -V Guadalinex.Suppletory.DiskA out/
		;;


	esac

	VAR=$1
done
