#!/bin/sh

[ -z "$1" ] && echo "Usage: $0 path-to-debs" && exit 1

RET=""

get_dir () {
	DIRPOOL=""
	DIRPOOL=$(dpkg --field $1 Source)
	[ -z "$DIRPOOL" ] && DIRPOOL=$(dpkg --field $1 Package)
	RET="pool/main/$(echo $DIRPOOL | cut -c 1)/$DIRPOOL"
	echo $RET
}

VAR=$1

while [ ! -z "$VAR" ]
do
	shift

	case $VAR in
	-h|h)
		echo "Shout help, maybe you are lucky today..."
		;;
	*)
		[ ! -d $VAR ] && echo "The argument is not a directory!" && exit 1

		PACKAGES=$(find $VAR | grep -e "\.deb$")


		[ -z "$PACKAGES" ] && echo "There is no packages on this directory!" && exit 1

		# Create the pool/
		for x in $PACKAGES
		do
			DESTDIR=$(get_dir $x)
			[ ! -d $DESTDIR ] && mkdir -p $DESTDIR			
			cp $x $DESTDIR	
		done


		# Create the dist/
		[ -d dists/flamenco/main/binary-i386 ] || mkdir -p dists/flamenco/main/binary-i386 
		apt-ftparchive packages pool/ > dists/flamenco/main/binary-i386/Packages

		cp dists/flamenco/main/binary-i386/Packages dists/flamenco/main/binary-i386/Packages2
		gzip dists/flamenco/main/binary-i386/Packages2 
		mv dists/flamenco/main/binary-i386/Packages2.gz dists/flamenco/main/binary-i386/Packages.gz
		;;
	esac

	VAR=$1
done
