#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for copy the necessaries binaries for the live system into the initramfs

. /usr/share/initramfs-tools/hook-functions

if [ -e /usr/share/server-clone/conf/initramfs.conf ]; then
	. /usr/share/server-clone/conf/initramfs.conf
else
	exit 0
fi

if [ "${BOOT}" == "clone" ]; then
	LIVE_SCRIPTS="/usr/share/initramfs-tools/live_scripts"
	for f in $(cd ${LIVE_SCRIPTS} && \
	        find . \( -name '*.dpkg*' -prune -o -name '*~' -prune -o -name '.svn' -prune \) \
	                -o -type f -print); do
		dir=$(dirname ${f}  | sed 's|live|clone|g')
	        mkdir --parents ${DESTDIR}/scripts/${dir}
		cp -p ${LIVE_SCRIPTS}/${f} ${DESTDIR}/scripts/${dir}
	done
	CLONE_SCRIPTS="/usr/share/server-clone/clone_scripts"
	for f in $(cd ${CLONE_SCRIPTS} && \
	        find . \( -name '*.dpkg*' -prune -o -name '*~' -prune -o -name '.svn' -prune \) \
	                -o -type f -print); do
	        mkdir --parents ${DESTDIR}/scripts/$(dirname ${f})
		cp -p ${CLONE_SCRIPTS}/${f} ${DESTDIR}/scripts/$(dirname ${f})
	done
fi
