#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for loading modules necessaries for the live system into the initramfs

. /usr/share/initramfs-tools/hook-functions

if [ -e /usr/share/server-clone/conf/initramfs.conf ]; then
	. /usr/share/server-clone/conf/initramfs.conf
else
	exit 0
fi

if [ "${BOOT}" == "clone" ]; then
	if [ -e /usr/share/server-clone/conf/config.cfg ]; then
		cp -a /usr/share/server-clone/conf/config.cfg ${DESTDIR}/etc/
		UDHCPC_FILES="/usr/share/server-clone/conf/udhcpc/"
		mkdir -p ${DESTDIR}/etc/udhcpc 
		cp -p ${UDHCPC_FILES}/* ${DESTDIR}/etc/udhcpc/
	else
		exit 1
	fi
fi
