#! /bin/sh

PROJECT="${PROJECT:-guadalinex}"
CAPPROJECT="${CAPPROJECT:-Guadalinex}"
DIST="${DIST:-breezy}"

case $DIST in
	warty|hoary|breezy)
#		ARCHES="${ARCHES:-amd64 i386 powerpc}"
		ARCHES="${ARCHES:-i386}"
		;;
esac

GNUPG_DIR="$CDIMAGE_ROOT/secret/dot-gnupg"
SIGNING_KEYID=FBB75451

umask 002
