#!/bin/sh -e

. /usr/share/debconf/confmodule

#ARCH=`udpkg --print-architecture`

log() {
    logger -t uda-prepartman-message "info: $@"
}

db_input critical uda-prepartman-message/prepartman-message || [ $? -eq 30 ]
db_go

log "Showing UDA firstmessage"

exit 0
