#!/bin/sh

PREREQ="parted"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


. /etc/config.cfg
ROOT_PARTITION=$(echo $mountpoints | cut -d'-' -f 1)
ROOT_PARTITION=${ROOT_PARTITION#/:}
SWAP_PARTITION=$(echo $mountpoints | cut -d'-' -f 2)
SWAP_PARTITION=${SWAP_PARTITION#swap:}

## In order to avoid very weird bug with the mkfs.ext3
ln -s /proc/mounts /etc/mtab

# Format the partitions
mkfs.ext3 $ROOT_PARTITION >> /tmp/initramfs.debug 2>&1
mkswap $SWAP_PARTITION >> /tmp/initramfs.debug 2>&1

# Activate the swap
#swapon $SWAP_PARTITION >> /tmp/initramfs.debug 2>&1

# Mounting main partition
mkdir -p /mnt/dev/ >> /tmp/initramfs.debug 2>&1
mount -t ext3 $ROOT_PARTITION /mnt/dev/ >> /tmp/initramfs.debug 2>&1

