#!/bin/sh
# Partitioning the disk as the scheme:
#/dev/hda1  -> /
#/dev/hda2  -> swap

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Cheching if there is any activated swap and deactivating it. Just in case
#while [ "$(grep -q dev /proc/swaps ; echo $?)" == "0" ]; do
#        sync
#        swapoff -a >> /tmp/initramfs.debug 2>&1
#done

# Calculating the optimus swap partition size
let MEM=$(grep ^MemTotal /proc/meminfo | while read a b c ; do echo $b ; done)/1024

if [ $MEM -gt 256 ]
then
    let SWAP_SIZE=256*1024
else
    let SWAP_SIZE=$MEM*1024
fi

# Finding the first disk
#DISK=$(grep '[sh]d[a-g]' /proc/partitions | while read a b c d ; do echo $d | cut -c 0-3 ; done | sort -u | head -1)
# This method could fail if there is no any partition at the disk. So we try this:
DISK=$(for i in /sys/block/* ; do if [ `cat $i/size` != 0 ]; then echo ${i#/sys/block/} ; fi ;  done | grep '[sh]d[a-g]' | head -1)
L=$(echo $DISK | cut -c 1)
DISK="/dev/${DISK}"

#### Set up at the config.cfg if there is ide or scsi disk
sed -i "s|@@@|$L|g" /etc/config.cfg
####


# Now the size of the disk
DISK_SIZE=$(sfdisk -uM -s ${DISK})

# First partition is going to be the main partition and
# the size will be the disk size minus the swap partition size
let ROOT_SIZE=($DISK_SIZE-$SWAP_SIZE)/1024

# Let's break the disk ;-)
sfdisk -uM $DISK << EOF  >> /tmp/initramfs.debug 2>&1
,$ROOT_SIZE,L
,,S
EOF


