#!/bin/sh
# 

PREREQ="user"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


# To avoid fsck
touch ${rootmnt}/fastboot

cat <<EOF > ${rootmnt}/etc/fstab
# /etc/fstab: static file system information.
#
# <file system> <mount point>   <type>  <options>       <dump>  <pass>
proc            /proc           proc    defaults        0       0
sys             /sys            sysfs   defaults        0       0
EOF


cat <<EOF > ${rootmnt}/etc/rc2.d/S05disks.sh
#
# disks.sh	Search all the local disks and write them into the /etc/fstab.
#
# Version:	@(#)disks.sh  1.0  15-Oct-2005  juanje@interactors.coop
#

VERBOSE=yes
TMPTIME=0
[ -f /etc/default/rcS ] && . /etc/default/rcS
. /lib/lsb/init-functions

#
# Search local disks partitions
#
get_partitions ()
{
	echo \$(ls /dev/[sh]d[a-z]?*)
}

#
# Check filesystem
#
get_filesystem ()
{
	ret=\$(sudo file -s \$1)
	case \$ret in
		*ext3*)
			echo "\$1 ext3"
			;;
		*ext2*)
			echo "\$1 ext3"
			;;
		*reiserfs*)
			echo "\$1 reiserfs"
			;;
		*XFS*)
			echo "\$1 xfs"
			;;
		*vfat*)
			echo "\$1 vfat"
			;;
		*ntfs*)
			echo "\$1 ntfs"
			;;
		*swap*)
			echo "\$1 swap"
			;;
		*)
			echo "\$1 auto"
			;;
	esac
}

#
# Search for CD/DVDs
#
get_cdroms ()
{
	echo \$(head -3 /proc/sys/dev/cdrom/info | tail -1 | cut -f 3-)
}

#
# Create fstab
#
create_fstab ()
{
	if \$(grep rw /proc/cmdline) ; then
		defaults="    defaults,nls=utf8,noauto        0       2"
	else
		defaults="    ro,users,nls=utf8,noauto        0       2"
	fi
	partitions=\$(get_partitions)
	for part in \$partitions; do
		entry=\$(get_filesystem \$part)
		dev=\$(echo \$entry | cut -d ' ' -f 1 )
		fs=\$(echo \$entry | cut -d ' ' -f 2 )
		if [ "\$fs" == "swap" ] ; then
			entry="\${dev}	none	swap    sw              0       0"
		else
			mntpoint="/media/\${dev#/dev/}"
			mkdir -p \$mntpoint
			if [ "\$fs" == "ntfs" ]; then
				defaults=\$(echo \${defaults} | sed 's|users|user,umask=022|g')
			fi
			entry="\${dev}	\${mntpoint}	\${fs}\${defaults}"
		fi
		echo \$entry >> /etc/fstab
	done
	num=0
	cdroms=\$(get_cdroms)
	for cd in \$cdroms; do
		entry="/dev/\${cd}        /media/cdrom\${num}   udf,iso9660 ro,user,noauto  0       0"
		mkdir -p /media/cdrom\${num} >> /var/log/initramfs.debug 2>&1
		let num=num+1
		echo \$entry >> /etc/fstab
	done
	
}

get_device ()
{
	dev=\$(grep /.dirs/dev /proc/mounts | cut -d " " -f 1)
	echo \$dev
}

log_begin_msg "Searching local disks..."
create_fstab
rm -f /etc/mtab
cat /proc/mounts > /etc/mtab
mount -a  >> /var/log/initramfs.debug 2>&1
swapon -a >> /var/log/initramfs.debug 2>&1
device=\$(get_device)
mount \$device >> /var/log/initramfs.debug 2>&1
log_end_msg 

exit 0
EOF

${rootmnt}/bin/chmod +x ${rootmnt}/etc/rc2.d/S05disks.sh 
