#!/bin/sh
# 

PREREQ="hwdetect"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac



. /conf/initramfs.conf

# Fixing sudo problems with netapplet
mv ${rootmnt}/usr/bin/netapplet ${rootmnt}/usr/bin/netapplet.orig

cat <<EOF > ${rootmnt}/usr/bin/netapplet
#!/bin/sh

sudo /usr/bin/netapplet.orig \$*

EOF

${rootmnt}/bin/chmod +x ${rootmnt}/usr/bin/netapplet 


# Fixing find noleaf problems with unionfs
mv ${rootmnt}/usr/bin/find ${rootmnt}/usr/bin/find.orig

cat <<EOF > ${rootmnt}/usr/bin/find
#!/bin/sh
IFS=""
/usr/bin/find.orig -L -P \$@

EOF

${rootmnt}/bin/chmod +x ${rootmnt}/usr/bin/find


# Fixing reboot command and eject process from everywhere
mv ${rootmnt}/sbin/reboot ${rootmnt}/sbin/reboot.orig

cat <<EOF > ${rootmnt}/sbin/reboot
#!/bin/sh

chvt 1
/sbin/reboot.orig \$@

EOF

${rootmnt}/bin/chmod +x ${rootmnt}/sbin/reboot

# Setting right permissions for every dir in which we modify files from here
# Right now, they are: /sbin, /usr/bin
chmod 755 ${rootmnt}/sbin
chmod 755 ${rootmnt}/usr/bin

exit 0
