#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

SPLASH=false;
VESA=false;

for x in $(cat /proc/cmdline); do
	case $x in
	splash*)
		SPLASH=true;
		;;
	vga=*)
		VESA=true;
		;;
	esac
done

if [ $SPLASH = "true" ]; then
	insmod /lib/modules/`uname -r`/kernel/drivers/video/console/bitblit.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/console/font.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/console/tileblit.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/console/fbcon.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/cfbcopyarea.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/cfbfillrect.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/cfbimgblt.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/softcursor.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/vgastate.ko
	if [ $VESA = "true" ]; then
		insmod /lib/modules/`uname -r`/initrd/vesafb.ko
	else
		insmod /lib/modules/`uname -r`/kernel/drivers/video/vga16fb.ko
	fi
	mknod /dev/fb0 c 29 0
	for i in 0 1 2 3 4 5 6 7 8; do
		mknod /dev/tty$i c 4 $i
	done
	/sbin/usplash -c &
	sleep 1
fi
