#!/bin/sh

PREREQ=""
prereqs()
{
	echo "$PREREQ"
}
case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

SPLASH=false;
VESA=false;

for x in $(cat /proc/cmdline); do
	case $x in
	splash*)
		SPLASH=true;
		;;
	vga=*)
		VESA=true;
		;;
	esac
done

if [ $SPLASH = "true" -a $VESA = "false" ]; then
	insmod /lib/modules/`uname -r`/kernel/drivers/video/console/bitblit.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/console/font.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/console/tileblit.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/console/fbcon.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/cfbcopyarea.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/cfbfillrect.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/cfbimgblt.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/softcursor.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/vgastate.ko
	insmod /lib/modules/`uname -r`/kernel/drivers/video/vga16fb.ko
	mknod /dev/fb0 c 29 0
	mknod /dev/tty0 c 4 0
	/sbin/usplash -c &
fi
