#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
prereqs)
	prereqs
	exit 0
	;;
esac

if [ -x /sbin/usplash ]; then
	install -D /sbin/usplash ${DESTDIR}/sbin/usplash
fi

if [ -x /sbin/usplash_write ]; then
	install -D /sbin/usplash_write ${DESTDIR}/sbin/usplash_write
fi

. /usr/share/initramfs-tools/hook-functions

for x in fbcon vga16fb; do
    manual_add_modules ${x}
done
