#!/bin/sh
# Search the image in the local disks
PREREQ="network"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac


disks=""
for device in /sys/block/* ; do
        if [ -e ${device}/device ]; then
                disk=${device#/sys/block/}
                ls ${device}/${disk}* > /dev/null 2>&1
                if [ $? = 0  ]; then
                        for partition in ${device}/${disk}* ; do
                                disks="${disks} ${partition#${device}/}"
                        done
                else
                        disks="${disks} ${disk}"
                fi
        fi
done


modprobe -q isofs
mkdir -p /mnt/dev
found=n
for disk in $disks; do
	mount -t auto -o ro /dev/$disk /mnt/dev >> /tmp/initramfs.debug 2>&1
	if [ -e /mnt/dev/META/META.squashfs ]; then
		found=y
		break
	else
		umount /mnt/dev >> /tmp/initramfs.debug 2>&1
	fi
done
if [ x${found} = xy ]; then
	echo "LOCAL: Montada la imagen" >> /tmp/initramfs.debug
else
	echo "LOCAL: ERROR -> NO montada la imagen" >> /tmp/initramfs.debug
fi





