#!/bin/sh
# Get the image, putting in the rigth place and mount it

PREREQ="local"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Just to be sure
modprobe -q squashfs >> /tmp/initramfs.debug 2>&1
modprobe -q loop >> /tmp/initramfs.debug 2>&1

IMAGE=/mnt/image
mkdir -p ${IMAGE} >> /tmp/initramfs.debug 2>&1

mount -o loop -t squashfs /mnt/dev/META/META.squashfs $IMAGE >> /tmp/initramfs.debug 2>&1
if [ $? = 0 ]; then
	echo "SETUP_IMAGE: image mounted"  >> /tmp/initramfs.debug 2>&1
	exit 0
else
	echo "SETUP_IMAGE: ERROR -> image non mounted"  >> /tmp/initramfs.debug 2>&1
	exit 1
fi
