Document: ieee80211
Title: Debian ieee80211 Manual
Author: <insert document author here>
Abstract: This manual describes what ieee80211 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/ieee80211/ieee80211.sgml.gz

Format: postscript
Files: /usr/share/doc/ieee80211/ieee80211.ps.gz

Format: text
Files: /usr/share/doc/ieee80211/ieee80211.text.gz

Format: HTML
Index: /usr/share/doc/ieee80211/html/index.html
Files: /usr/share/doc/ieee80211/html/*.html

  
