.TH BASE-CONFIG 8
.SH NAMA
base-config \- Alat konfigurasi sistem basis Debian
.SH RINGKASAN
.B base-config [new]
.SH PENJELASAN
.BR base-config
merupakan program yang dijalankan saat pertama kali anda boot ke sistem
Debian anda yang baru diinstal. Program ini membimbing anda melalui
tahap-tahap pengaturan sistem, mengunduh (mendownload) perangkat lunak tambahan,
dan seterusnya. Program ini dapat dijalankan lagi di kemudian hari,
apabila anda ingin mengulangi proses yang sama lagi.
.SH IMPLEMENTASI
.BR base-config
menghasilkan pilihan menu dari isi berkas
.BR /usr/lib/base-config/ ,
dan dari templet-templet debconf.
.P
Berkas-berkas .mnu dalam /usr/lib/base-config mengatur apakah sebuah item menu
muncul hanya saat instalasi baru (Only-New: True), apakah debconf dapat
telah jalan ketika item tersebut dijalankan (Debconf: true), urutan numerik
mengatur peletakan dalam menu. Jika sebuah berkas .mnu berisi "Exit-Menu: true",
maka base-config akan berhenti setelah menjalankan item menu tersebut. Terakhir,
baris "Changes-menu: true" akan membuat base-config membangun kembali menu
setelah menjalankan item menu tersebut.

.P
Berkas-berkas .tst pada /usr/lib/base-config/ akan dijalankan ketika
base-config membangun menu dan mesti mengembalikan nilai benar (true) agar item
menu tersebut muncul pada menu.

.P
Item-item menu diambil dari debconf, dengan melihat item-item pada
basis data debconf yang dinamakan base-config/menu/sesuatu.

.P
Saat sebuah item menu dipilih, program yang sesuai pada /usr/lib/base-config
akan dijalankan. Jika ini merupakan instalasi perdana pada sebuah sistem Debian
yang baru, program akan menerima "new" pada argumen pertama.

.P
.B base-config
memeriksa nilai kembalian dari tiap program. Jika sebuah program mengembalikan
nilai bukan nol, maka menu utama akan ditampilkan (ini bisa melibatkan 
penurunan prioritas debconf).

.P
Paket-paket lain dapat menaruh berkas-berkas pada 
.BR /usr/lib/base-config/ ,
dan menambahkan judul menu pada debconf, dan mereka akan ditambahkan pada menu.
Sangat disarankan agar program-program tersebut berinteraksi dengan pengguna
sepenuhnya melalui debconf, sehingga konfigurasi basis dapat mempertahankan
tampilan yang konsisten dan profesional.

.P
Hal berguna lainnya untuk distribusi yang dikustomisasi adalah berkas
/usr/share/base-config/debconf-seed. Bila direktori tersebut ditemukan,'
semua berkas didalamnya akan dimuat dalam basis data debconf menggunakan
.BR debconf-set-selections (1)

.SH BERKAS-BERKAS
Setiap kali base-config dijalankan, akan ditulis log pada
.BR /var/log/base-config.log .
.BR /var/log/base-config.timings
berisi informasi waktu untuk dijalankan dengan log.
Ini memungkinkan pengulangan jalannya base-config dengan menggunakan
utilitas
.BR replay (1)
.P
.BR /var/log/installer/cdebconf ,
jika ada, digunakan oleh
.B base-config
pada instalasi baru untuk mengambil nilai-nilai dari tahap pertama
instalasi debian-installer.
.SH LINGKUNGAN
Variabel-variabel lingkungan berikut mempengaruhi
.BR base-config .
Nilai-nilai ini dapat diatur saat menjalankan, atau untuk instalasi baru,
dapat diberikan pada kernel melalui baris perintah
.BR lilo (8)
(atau boot loader lainnya). Lihat dokumentasi boot loader anda untuk informasi
detil. Sebagai contoh, lilo dapat diboot sebagai berikut:
"linux DEBIAN_FRONTEND=readline".
.TP
.B DEBIAN_FRONTEND
.TP
.B DEBIAN_PRIORITY
.TP
.B DEBCONF_DEBUG
.TP
.B DEBCONF_TERSE
Mengatur beragam hal mengenai
.BR debconf (7)
.TP
.B KEEP_DEBS
Secara bawaan,
.B base-config
menghapus berkas-berkas deb yang digunakan
.BR debootstrap (8) 
untuk menginstal sistem. Ini berguna pada instalasi dimana ruang hard disk
sangat terbatas. Jika anda tidak ingin ini dilakukan, dan ingin berkas-berkas
deb tetap dijaga, atur nilai variabel ini menjadi "yes".

.SH PENULIS
Joey Hess <joeyh@debian.org>
.SH PENERJEMAH
Parlin Imanuel Toh <debian-l10n-id@gurame.fisika.ui.ac.id>
