.TH TERMWRAP 8
.SH NAMA
termwrap \- terminal wrapper
.SH RINGKASAN
.B termwrap [-nnt] perintah [args]
.SH PENJELASAN
.BR termwrap
digunakan untuk menjalankan
.BR base-config (8)
pada sistem Debian yang baru dipasang. Ia meneliti lingkungan,
memperhatikan pengaturan lokal, dan jenis konsol yang tersedia,
dan kemudian menjalankan program terminal yang sesuai. Sebagai
contoh, pada konsol Linux dan lokal Jepang, ia akan menjalankan jfterm.
Program yang diberikan akan dijalakan pada terminal tersebut (jika tersedia).
.SH OPSI-OPSI
.TP
.I "-nnt"
Jangan menjalankan terminal yang lain.
.SH PENERJEMAH
Parlin Imanuel Toh <debian-l10n-id@gurame.fisika.ui.ac.id>
