.\" (c) 2003 Software in the Public Interest
.\" Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
.\" y revisada por Santiago Vila <sanvila@unex.es>
.\" Está basada en la página de manual original:
.\" versión 1.10 del CVS de
.\" /cvs/debian-doc/manpages/english/base-config/base-config.8

.TH BASE-CONFIG 8
.SH NOMBRE
base-config \- configuración del sistema base de Debian
.SH SINOPSIS
.B base-config [new]
.SH DESCRIPCIÓN
.BR base-config
es el programa que se ejecutó la primera vez que arrancó en su sistema Debian
recién instalado. base-config termina de configurar el sistema, descarga
programas adicionales... El programa puede ejecutarse en cualquier
momento posterior para realizar el mismo proceso de nuevo.
.SH IMPLEMENTACIÓN
.BR base-config
genera un menú de elecciones con los contenidos de
.BR /usr/lib/base-config/ ,
y de las plantillas de debconf.
.P
Los ficheros .mnu de /usr/lib/base-config/ controlan si el elemento del menú
aparece sólo en nuevas instalaciones (Only-New: true), si debconf puede estar
siendo ejecutado en el momento en el que se ejecute el elemento (Debconf: true).
Una opción numérica "Order" controla el lugar en el menú. Si el fichero .mnu
contiene "Exit-Menu:true", base-config terminará después de ejectuar ese
elemento del menú. Finalmente, una línea "Changes-Menu: true" hará que
base-config reconstruya el menú después de ejecutar el elemento del menú.
.P
Los ficheros .tst de /usr/lib/base-config/ se ejecutan cuando base-config
construye el menú y debe devolver "true" para que ese elemento aparezca en el
menú.
.P
Los elementos del menú se toman de debconf, buscando los elementos en la base
de datos de debconf llamada base-config/menu/loquesea.
.P
Cuando se selecciona elemento del menú, se ejecuta el programa correspondiente en
/usr/lib/base-config. Si ésta es la primera instalación en un sistema recién
instalado, entonces el programa recibe "new" como su primer argumento.
.P
.B base-config
comprueba los valores devueltos por cada programa. Si un programa devuelve un
valor distinto de cero, se muestra el menú principal (puede que esto implique
bajar la prioridad de debconf).
.P
Normalmente el usuario es guiado de arriba abajo de un elemento del menú en
otro a medida que cada uno de ellos se completa con éxito. Si un elemento del
menú necesita volver a otro anterior o saltar alguno de los posteriores, puede
hacerlo escribiendo el nombre del siguiente elemento del menú al que saltar en
el fichero "jump-to" en el directorio actual.
.SH FICHEROS
Cualquier ejecución de base-config se registra en 
.BR /var/log/base-config.log .
.BR /var/log/base-config.timings
contiene información de los tiempos que van con el registro. Esto permite volver
a ver la ejecución de base-config usando la utilidad
.BR replay (1) .
.P
Si existe
.BR var/log/installer/cdebconf ,
.B base-config
lo usa en nuevas instalaciones para obtener valores de la primera etapa de
instalación del "debian-installer".
.P
Otros paquetes pueden dejar ficheros en
.BR /usr/lib/base-config/ ,
y añadir títulos de menú en debconf, y serán añadidos al menú. Es
altamente recomendable que cualquiera de estos programas se comunique con el
usuario totalmente a través de debconf, de esta forma, la configuración mantiene
un aspecto consistente y profesional.
.P
Otra cosa útil para las distribuciones personalizadas es
/usr/share/base-config/debconf-seed. Si ese directorio existe, todos los
ficheros dentro de él se cargarán en la base de datos de debconf usando
.BR debconf-set-selections (1)
.P
Si debian-installer crea el fichero /var/log/installer/debconf-seed,
también se incorporará a la base de datos de debconf.
.SH ENTORNO
Las siguientes variables de entorno influencian a
.BR base-config .
Estas variables pueden establecerse en tiempo de ejecución, o para nuevas
instalaciones, puede pasarse al núcleo en la línea de órdenes de
.BR lilo (8)
(u otro gestor de arranque). Consulte la documentación de su gestor de arranque
para más detalles. Por ejemplo, lilo puede arrancarse con algo como "linux
DEBIAN_FRONTEND=readline".
.TP
.B DEBIAN_FRONTEND
.TP
.B DEBIAN_PRIORITY
.TP
.B DEBCONF_DEBUG
.TP
.B DEBCONF_TERSE
Controlan varias cosas de
.BR debconf (7)
.TP
.B KEEP_DEBS
Por omisión,
.B base-config
borra los debs que usa
.BR debootstrap (8) 
para instalar el sistema. Es útil para instalaciones en discos muy
pequeños. Si no quiere que esto se realice, y prefiere que se conserven los
debs, establezca esta variable a "yes".
.SH AUTOR
Joey Hess <joey@debian.org>
.SH TRADUCTOR
Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>
