.TH TERMWRAP 8
.SH NAME
termwrap \- terminal wrapper
.SH SYNOPSIS
.B termwrap [-nnt] command [args]
.SH DESCRIPTION
.BR termwrap
is used to execute
.BR base-config (8)
on newly installed Debian systems. It examines the environment,
taking note of locale settings, and what type of console is
available, and runs an appropriate terminal program. For example, at the
Linux console and in a Japanese locale, it runs jfterm. The specified
command is run inside the terminal program (if any).
.SH OPTIONS
.TP
.I "-nnt"
Don't run another terminal.
