#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for copy the .desktop who launch the live installer into the initramfs

. /usr/share/initramfs-tools/hook-functions

. /etc/mkinitramfs/initramfs.conf

if [ "${BOOT}" == "live" ]; then
	install -m 644 /etc/mknitramfs/install.desktop ${DESTDIR}/conf/install.desktop
fi
