#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for copy the necessaries binaries for the live system into the initramfs

. /usr/share/initramfs-tools/hook-functions

. /etc/mkinitramfs/initramfs.conf

if [ "${BOOT}" == "live" ]; then
	for x in bin sbin ; do
		copy_exec /usr/share/initramfs-tools/${x}/* ${DESTDIR}/${x}/
	done
fi
