#!/bin/sh

set -e

# source debconf library
. /usr/share/debconf/confmodule


if [ "$1" = "reconfigure" ] || [ -n "$DEBCONF_RECONFIGURE" ]; then
  RECONFIGURE=true
else
  RECONFIGURE=
fi

if [ -z "$2" ]; then
  FIRSTINST="yes"
fi
      
#Hack: it's necessary to update the kernel database after copy the unonfs module
# and we have to put here the kernel version
KVERSION="2.6.12-9-386"

depmod -ea $KVERSION
