#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Hooks for copy the necessaries binaries for the live system into the initramfs

. /usr/share/initramfs-tools/hook-functions

. /etc/mkinitramfs/initramfs.conf

if [ "${BOOT}" == "live" ]; then
	LIVE_SCRIPTS="/usr/share/initramfs-tools/live_scripts"
	for f in $(cd ${LIVE_SCRIPTS} && \
	        find . \( -name '*.dpkg*' -prune -o -name '*~' -prune \) \
	                -o -type f -print); do
	        mkdir --parents ${DESTDIR}/scripts/$(dirname ${f})
		cp -p ${LIVE_SCRIPTS}/${f} ${DESTDIR}/scripts/$(dirname ${f})
	done
	LIVE_DIR="/usr/share/initramfs-tools"
	cp -p ${LIVE_DIR}/bin/* ${DESTDIR}/sbin/

fi
