#!/bin/sh
# Partitioning the disk as the scheme:
#/dev/hda1  -> /
#/dev/hda2  -> swap

PREREQ="tmpfs"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions

LOG="/tmp/initramfs.debug"

exec 2>> $LOG 2>&2

set -x

# Calculating the optimus swap partition size
let MEM=$(grep ^MemTotal /proc/meminfo | while read a b c ; do echo $b ; done)/1024

if [ $MEM -gt 256 ]
then
    let SWAP_SIZE=256*1024
else
    let SWAP_SIZE=$MEM*1024
fi

# Finding the first disk
disks=$(
for i in /sys/block/* ; do
    if [ `cat $i/size` != 0 ]; then
        echo ${i#/sys/block/}
    fi
done | grep '[sh]d[a-g]'
)

DISK=""
for disk in $disks ; do
    rem=$(cat /sys/block/${disk}/removable 2> /dev/null)
    if [ "$rem" = 0 ]; then
    	DISK="$disk"
	break
    fi
done

L=$(echo $DISK | cut -c 1)
DISK="/dev/${DISK}"

log_begin_msg "Particionando el disco ${DISK}..."

#### Set up at the config.cfg if there is ide or scsi disk
sed -i "s|@@@|$L|g" /etc/config.cfg
####


# Now the size of the disk
DISK_SIZE=$(sfdisk -uM -s ${DISK})

# First partition is going to be the main partition and
# the size will be the disk size minus the swap partition size
let ROOT_SIZE=$DISK_SIZE-$SWAP_SIZE
let ROOT_SIZE=$ROOT_SIZE/1024

# Let's break the disk ;-)
sfdisk -uM $DISK << EOF  >> $LOG
,$ROOT_SIZE,L
,,S
EOF

log_end_msg $?
