#!/bin/sh
# Get the image, putting in the rigth place and mount it

PREREQ="network"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions

LOG="/tmp/initramfs.debug"

exec 2>> $LOG 2>&2

set -x

log_begin_msg "Montando la imagen..."

# Just to be sure
modprobe -q squashfs  >> /tmp/initramfs.debug 
modprobe -q loop >> /tmp/initramfs.debug 

IMAGE=/mnt/image
mkdir -p ${IMAGE} 

mknod /dev/loop0 b 7 0 
mount -r -o loop -t squashfs /mnt/dev/META/META.squashfs $IMAGE || panic "Fallo al intentar montar la imagen"

log_end_msg $?

