#!/usr/bin/python
# -*- coding: utf-8 -*-

"""
Este script genera una iso con un suplemento para Guadalinex 2005
"""

import os

DISTCODENAME = 'flamenco'
MASTERDIR = './master' 

os.system('mkdir ./master')


class ConfigParser(dict):

    def __init__(self):
        dict.__init__(self)
        
        #Fill obligatory fields.
        self['NAME'] = 'Default Name'
        self['DESC'] = 'Default Description'
        self.configure()

    def configure(self):
        objfile = open('./config')
        for line in objfile.readlines():
            if not line.strip().startswith('#'):
                try:
                    key, value = line.split(None, 1)
                    self[key] = value.strip()
                except:
                    pass
        


def main():
    ############################################################################
    # Step 1:  Generate debian repository (dists and pool directories)
    ############################################################################
    
    PACKAGESDIR = MASTERDIR + '/dists/' + DISTCODENAME + '/main/binary-i386'
    os.system('mkdir -p ' + PACKAGESDIR)
    os.system('mkdir ' + MASTERDIR + '/pool')
    os.system('cp -a ./debs/* ' + MASTERDIR + '/pool')
    
    os.chdir(MASTERDIR)
    os.system('dpkg-scanpackages ./pool /dev/null > ../' + PACKAGESDIR + '/Packages')
    os.chdir('..')
    os.system('yes | gzip '+ PACKAGESDIR + '/Packages')
    
    
    ############################################################################
    # Step 2: Generate README.diskdefines
    ############################################################################

    config = ConfigParser()
    objfile = open(MASTERDIR + '/README.diskdefines', 'w')
    objfile.write ('#define DISKNAME ' + config['NAME'] + '\n')
    #Default URI
    objfile.write ('#define URI     \n')

    for ele in config.get_uris():
        objfile.write('#define URI ' + ele)

    objfile.close()



if __name__ == "__main__":
    main()
