.TH APT-SETUP 8
.SH NOME
apt-setup \- adiciona fontes de download para o apt
.SH RESUMO
.B apt-setup [probe]
.SH DESCRIÇÃO
.BR apt-setup
é um programa interativo que simplifica a adição de fontes no arquivo
sources.list do apt. Ele conhece todos os maiores espelhos (mirrors)
debian e pode ajudá-lo a selecionar um. Pode até mesmo usar o
.BR apt-cdrom (8)
para adicionar CDs.
.SH OPÇÕES
.TP
.I "probe"
Por padrão nenhuma adição de CDs é feita. Passar "probe" como o primeiro
argumento para este programa fará com que o mesmo procure por um CD no
drive em sua inicialização e o adicione ao sources.list. Isto é útil em
instalações iniciais do debian para minimizar a interação com o usuário.
.SH AUTOR
Joey Hess <joey@kitenet.net>
