#!/bin/sh
# Exit base-config.
set -e

# Finally, put the real inittab into place and tell init.
if [ -f /etc/inittab.real ]; then
	mv -f /etc/inittab.real /etc/inittab
	telinit q >/dev/null
	# Clear the screen, in preparation for the login prompt
	clear
fi
