.TH "GPARTED" "1" 
.SH "NAME" 
gparted \(em a graphical partitioning tool 
.SH "SYNOPSIS" 
.PP 
\fBgparted\fR [\fB-?, \fP\fB\-\-help\fP]  [\fB\-\-installer\fP]  [\fB\-\-display=\fIX\fR\fP]  
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBgparted\fR command. 
.PP 
This manual page was written for the \fBUbuntu\fP distribution 
because the original program does not have a manual page. 
 
.PP 
\fBgparted\fR helps you to visually arrange your  
partitions. It makes use of the libparted library to accomplish that. 
Just start it from the menu. 
.IP "\fB-?\fP           \fB\-\-help\fP         " 10 
Show summary of options. 
.IP "\fB\-\-display=\fIX\fR\fP         " 10 
Specifies the X display that gparted will use. 
.IP "\fB\-\-installer\fP         " 10 
NOTE: You should never have to use this, this is an option 
that is provided for UbuntuExpress and does some different 
assumptions. 
.SH "AUTHOR" 
.PP 
This manual page was written by Daniel Holbach dh@mailempfang.de for 
the \fBUbuntu\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Mon 23 Jan 2006, 12:29 
