#! /bin/sh
# 
# The usplash script makes sure that usplash exits at the end of 
# the boot sequence and re-run the console-screen.sh script to make
# sure that the console fonts are actually set
#
#		Written by Miquel van Smoorenburg <miquels@cistron.nl>.
#		Modified for Debian 
#		by Ian Murdock <imurdock@gnu.ai.mit.edu>.
#
# Version:	@(#)skeleton  1.9  26-Feb-2001  miquels@cistron.nl
#

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/sbin/usplash
NAME=usplash
DESC="Userspace bootsplash utility"

test -x $DAEMON || exit 0

set -e

usplash_quit() {
	if pidof usplash > /dev/null; then
	        # save to use chvt here because X can't run (otherwise
                # usplash wouldn't runing)
	        chvt 1
		if [ -x /etc/init.d/console-screen.sh ]; then
			/etc/init.d/console-screen.sh
		fi
	fi
}

case "$1" in
  start)
	usplash_quit
	;;
  stop)
	usplash_quit
	;;
  *)
	N=/etc/init.d/$NAME
	# echo "Usage: $N {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $N {start|stop}" >&2
	exit 1
	;;
esac

exit 0
