#! /bin/sh

set -e

#DEBHELPER#

case "$1" in
	configure)
		if dpkg --compare-versions "$2" eq 0.1-12; then
			update-alternatives --remove usplash-artwork.so /usr/share/usplash/usplash-default.so
		fi

		update-alternatives --install /usr/lib/usplash/usplash-artwork.so usplash-artwork.so /usr/lib/usplash/usplash-default.so 10
		;;
esac
