.TH "cxacru-fw" "1" 
.SH "NAME" 
cxacru-fw \(em Firmware extractor for Conexant AccessRunner ADSL USB modems 
.SH "SYNOPSIS" 
.PP 
\fBcxacru-fw\fR [\fB-h\fP]  [\fB\-\-help\fP]  [\fB\-\-usage\fP]  [\fB\-\-version\fP] \fBinfinle outfile\fR 
.SH "DESCRIPTION" 
.PP 
This manual page documents briefly the 
\fBcxacru-fw\fR command. 
.PP 
This is a firmware extractor for Conexant AccessRunner ADSL USB modems 
.PP 
Report bugs to (accessrunner-general at lists dot sourceforge dot net). 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. 
.IP "\fB-h\fP           \fB\-\-help\fP         " 10 
Show summary of options. 
.IP "\fB-u\fP           \fB\-\-usage\fP         " 10 
Show a short usage message. 
.IP "\fB-v\fP           \fB\-\-version\fP         " 10 
Print the program version 
.SH "AUTHOR" 
.PP 
This manual page was written by vjrj vjrj@tid.es for 
the \fBDebian\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License, Version 2 any  
later version published by the Free Software Foundation. 
 
.PP 
On Debian systems, the complete text of the GNU General Public 
License can be found in /usr/share/common-licenses/GPL. 
 
.\" created by instant / docbook-to-man, Mon 31 Oct 2005, 13:18 
