#!/usr/bin/python2.4

# Copyright (C) 2004-2005 Ross Burton <ross@burtonini.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA 02111-1307 USA

if __name__ == "__main__":
        import sys, gettext, os
        import pygtk; pygtk.require("2.0")
        import gtk, gtk.glade

        gettext.bindtextdomain("gnome-app-install", "/usr/share/locale")
        gettext.textdomain("gnome-app-install")
        gtk.glade.bindtextdomain("gnome-app-install", "/usr/share/locale")
        gtk.glade.textdomain("gnome-app-install")

	if os.geteuid() != 0:
		_ = gettext.gettext
		dialog = gtk.MessageDialog(None, 0, gtk.MESSAGE_ERROR,
					   gtk.BUTTONS_OK,
					   _("You need to be root to run this "
					     "program."))
		dialog.run()
		dialog.destroy()
		sys.exit(1)


        sys.path.insert(0, "/usr/lib/gnome-app-install")
	from AppInstall import AppInstall
	desktop_folder = os.path.join(sys.argv[1],"guadalinex-suplementos-apps")
        app = AppInstall(desktop_folder, desktop_folder, [sys.argv[0]] + sys.argv[2:])
        gtk.main()
