#
# Makefile for USB ATM/xDSL drivers
#

#obj-$(CONFIG_USB_CXACRU)	+= cxacru.o
#obj-$(CONFIG_USB_SPEEDTOUCH)	+= speedtch.o
#obj-$(CONFIG_USB_ATM)		+= usbatm.o
#obj-$(CONFIG_USB_XUSBATM)	+= xusbatm.o
obj-m	+= cxacru.o
obj-m	+= speedtch.o
obj-m	+= usbatm.o
obj-m	+= xusbatm.o
