\" translation of base-config.8 CVS revision 1.7
.TH BASE-CONFIG 8
.SH NAZWA
base-config \- konfiguracja podstawowego systemu Debian
.SH SK£ADNIA
.B base-config
.SH OPIS
.BR base-config
to program uruchamiany po pierwszym starcie nowo zainstalowanego systemu Debian.
Prowadzi on u¿ytkownika przez konfiguracjê systemu, pobieranie dodatkowego
oprogramowania, i tak dalej. Program ten mo¿na uruchomiæ w dowolnym
momencie aby przej¶æ przez ten proces ponownie.
.SH IMPLEMENTACJA
.BR base-config
jest zaimplementowany jako skrypt uruchamiaj±cy kolejno wszystkie programy
w katalogu
.BR /usr/lib/base-config/ ,
w kolejno¶ci numerycznej. Je¶li jest to pierwsze uruchomienie po zainstalowaniu
systemu, ka¿dy program otrzymuje jako pierwszy argument wyraz "new".
.P
.B base-config
sprawdza kody wyj¶cia ka¿dego z programów. Mog± one zwracaæ kody > 0 i < 100
aby zasygnalizowaæ b³êdy. Kody od 101 do 200 s³u¿± do przeskakiwania do programu
o numerze najbli¿szym zwróconej liczbie pomniejszonej o 100, dziêki czemu mo¿na
poruszaæ siê w procesie konfiguracji systemu podstawowego w przód i w ty³.
.P
Pakiety mog± instalowaæ programy w katalogu
.BR /usr/lib/base-config/ ,
dziêki czemu stan± siê one czê¶ci± procesu konfiguracji. Zaleca siê, aby programy
te komunikowa³y siê z u¿ytkownikiem wy³±cznie przy pomocy programu systemu
debconf, dziêki czemu konfiguracja systemu podstawowego uzyska jednolity
i profesjonalny wygl±d.
.SH PLIKI
Ka¿de uruchomienie programu base-config jest zapisywane do pliku 
.BR /var/log/installer.log .
.P
Je¶li istnieje plik
.BR /root/dbootstrap_settings ,
jest czytany przez
.B base-config ,
a zdefiniowane w nim ró¿ne zmienne ¶rodowiskowe wp³ywaj± na dzia³anie
programu. Samo istnienie tego pliku, tworzonego przez program
.B dbootstrap
(program instalacyjny boot-floppies) podczas instalacji systemu, powoduje ¿e
.B base-config
zachowuje siê tak, jakby by³ uruchomiony bezpo¶rednio po zainstalowaniu systemu.
.SH ¦RODOWISKO
Nastêpuj±ce zmienne ¶rodowiskowe wp³ywaj± na dzia³anie
.BR base-config .
Mo¿na je ustawiæ przy uruchomieniu programu lub (w przypadku instalacji
nowego systemu) mo¿na je podaæ j±dru przy pomocy linii poleceñ
.BR lilo (8)
lub innego programu ³aduj±cego. Wiêcej informacji na temat przekazywania
parametrów j±dru mo¿na znale¼æ w dokumentacji danego programu ³aduj±cego. W
przypadku lilo mo¿na za³adowaæ system na przyk³ad w nastêpuj±cy sposób: "linux
DEBIAN_FRONTEND=readline".
.TP
.B DEBIAN_FRONTEND
.TP
.B DEBIAN_PRIORITY
.TP
.B DEBCONF_DEBUG
.TP
.B DEBCONF_TERSE
Wp³ywaj± na dzia³anie systemu
.BR debconf (8)
.TP
.B KEEP_BASE_DEBS
Domy¶lnie
.B base-config
usuwa pakiety .deb, których
.BR debootstrap (8)
u¿y³ do zainstalowania systemu podstawowego. Jest to przydatne w przypadku
instalacji na bardzo ma³ych dyskach. Je¶li nie chcesz, aby pakiety by³y
kasowane, ustaw warto¶æ tej zmiennej na "yes".
.SH AUTOR
Joey Hess <joey@kitenet.net>
