#!/bin/sh -e

# This package does use debconf, but there is no config script.
. /usr/share/debconf/confmodule

if [ "$1" = configure ] && [ -n "$2" ] && dpkg --compare-versions "$2" lt 2.00; then
	# Clean up old debconf questions that are no longer in this package.
	db_unregister base-config/make-user 			|| true
	db_unregister base-config/md5 				|| true
	db_unregister base-config/password-empty 		|| true
	db_unregister base-config/password-mismatch		|| true
	db_unregister base-config/root-password			|| true
	db_unregister base-config/root-password-again		|| true
	db_unregister base-config/shadow			|| true
	db_unregister base-config/user-fullname			|| true
	db_unregister base-config/user-password			|| true
	db_unregister base-config/user-password-again		|| true
	db_unregister base-config/username			|| true
	db_unregister base-config/username-bad			|| true
	db_unregister base-config/keymap-failed			|| true
	db_unregister base-config/selection-path		|| true
	db_unregister tzconfig/settings				|| true
	db_unregister apt-setup/distribution			|| true
	db_unregister apt-setup/http_proxy			|| true
fi

if [ "$1" = configure ] && [ -n "$2" ] && dpkg --compare-versions "$2" lt 2.53.1; then
	# apt-setup and tzsetup used to leave seen flags set after running.
	# the new method, to better support preseeding, is to unset them
	# after asking a question. So unset all the flags to support
	# upgrades from old version.
	for q in mirror/suite mirror/http/proxy apt-setup/uri_type \
		apt-setup/country apt-setup/mirror apt-setup/hostname \
		apt-setup/directory apt-setup/baddir apt-setup/not-mirror \
		apt-setup/cd/dev apt-setup/cd/bad apt-setup/cd/another \
		apt-setup/non-free apt-setup/contrib apt-setup/badsource \
		apt-setup/another apt-setup/badedit \
		apt-setup/security-updates \
		apt-setup/security-updates-failed \
		tzconfig/gmt tzconfig/change_timezone \
		tzconfig/choose_country_zone/US \
		tzconfig/choose_country_zone/CA \
		tzconfig/choose_country_zone/BR \
		tzconfig/choose_country_zone_single \
		tzconfig/choose_country_zone_multiple \
		tzconfig/geographic_area tzconfig/verify_choices \
		tzconfig/select_zone/Atlantic \
		tzconfig/select_zone/Indian \
		tzconfig/select_zone/Pacific \
		tzconfig/select_zone/SystemV \
		tzconfig/select_zone/Etc \
		tzconfig/select_zone/Africa \
		tzconfig/select_zone/America \
		tzconfig/select_zone/US \
		tzconfig/select_zone/Canada \
		tzconfig/select_zone/Asia \
		tzconfig/select_zone/Australia \
		tzconfig/select_zone/Europe
	do
		db_fset $q seen false || true
	done
fi

#DEBHELPER#
