#!/bin/sh -e

. /usr/share/debconf/confmodule

ARCH=`udpkg --print-architecture`

log() {
    logger -t uda-firstmessage "info: $@"
}

db_title "Bienvenido"
db_input critical "uda-firstmessage/firstmessage" || [ $? -eq 30 ]
db_go

log "Mostrado UDA firstmessage"

exit 0
