#!/bin/sh

PREREQ=""

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

. /scripts/functions

LOG="/tmp/initramfs.debug"

 exec 2>> $LOG 2>&2

set -x

log_begin_msg "Copiando configuraciones y logs..."


# Copy the client config
cp -a /etc/config.cfg ${rootmnt}/etc/config.cfg 

# Copy the logs to the new system
ln -fs /tmp/initramfs.debug ${rootmnt}/var/log/initramfs.debug

# Changed inittab to launch netcloner instead second runlevel
sed -i -e 's|\(^l2:2:wait:\)\(/etc/init.d/rc.*\)|\1/usr/sbin/progressbar|' ${rootmnt}/etc/inittab

# Launch some ttys for debugging
sed -i -e "s|^\([^:]*:[^:]*:[^:]*\):.*getty.*\<\(tty[0-9]*\).*$|\1:/bin/login -f root </dev/\2 >/dev/\2 2>\&1|" ${rootmnt}/etc/inittab

# Ceaning up the start runlevel to avoid messing with the local hw
for file in anacron postfix hwclock.sh hwclockfirst.sh checkfs.sh checkroot.sh hdparm ntpdate mountall.sh networking ; do
        echo "deleting ${rootmnt}/etc/init.d/${file}..." >> /tmp/initramfs.debug
        : > ${rootmnt}/etc/init.d/${file}
done

log_end_msg $?
