.TH BASE-CONFIG 8
.SH NOME
base-config \- Configuração do sistema básico Debian
.SH RESUMO
.B base-config
.SH DESCRIÇÃO
.BR base-config
é o programa que foi executado quando você reiniciou a primeira vez
em seu novo sistema debian instalado. Ele o guia através de
configurações de seu sistema a o download de software adicional.
O programa pode ser executado posteriormente a qualquer momento para
guiá-lo essencialmente através do mesmo processo novamente.
.SH IMPLEMENTAÇÂO
.BR base-config
é implementado como um script wrapper que executa cada programa
em /usr/lib/base-config/, em ordem numérica. Se esta é uma nova
instalação em um sistema debian, cada programa recebe "new" como
seu primeiro argumento.
.P
base-config checa o código de retorno de cada um dos programas. Programas
podem retornar > 0 e < 10 para indicar erros. Códigos de retorno entre 10
e 100 podem ser usados para pular para o programa mais próximo do número
retornado. o qual pode ser usado para pular para trás ou para frente no
processo base-config.
.P
Outros pacotes podem colcar programas em /usr/lib/base-config/ e estes
programas farão parte do processo de configuração do sistema básico.
É fortemente recomendado que qualquer um destes programas se comunique
com o usuário completamente através do debconf, assim a configuração
básica manterá uma aparência consistente e profissional.
.SH ARQUIVOS
Cada execução de base-config é registrada em /var/log/installer.log.
.P
/root/dbootstrap_settings, caso exista, é usado por base-config e diversas
variáveis de ambientes definidas neste arquivo são usadas para controlar
o comportamento de base-config. A mera presença deste arquivo, o qual é
criado pelo dbootstrap durante uma nova instalação, faz com que
base-config faça tudo que ele faria somente em uma nova instalação.
.SH AMBIENTE
As seguintes variáveis de ambiente influenciam base-config. Estas
variáveis podem ser definidas em tempo de execução, ou para novas
instalações, podem ser passadas para o kernel na linha de comando do lilo
(ou outro carregador de inicialização). Consulte a documentação de seu
carregador de inicialização local para detalhes. Por exemplo, o lilo pode
ser iniciado com algo como "linux DEBIAN_FRONTEND=readline".
.TP
.B DEBIAN_FRONTEND
.TP
.B DEBIAN_PRIORITY
.TP
.B DEBCONF_DEBUG
.TP
.B DEBCONF_TERSE
Controla várias coisas sobre o debconf. Veja
.BR debconf (7)
.TP
.B KEEP_BASE_DEBS
Por padrão, base-config apaga os pacotes deb que o debootstrap utiliza
para instalar o sistema básico. Isto é útil em instalações em discos
muito pequenos. Caso você não queira que isso seja feito, e prefira que
os pacotes deb sejam mantidos, configure esta variável para "yes".
.SH AUTOR
Joey Hess <joey@kitenet.net>
