.\" (c) 2003 Software in the Public Interest
.\" Esta traducción ha sido realizada por Rubén Porras Campo <nahoo@inicia.es>
.\" Está basada en la página de manual original:
.\" versión 1.1 del CVS de
.\" /cvs/debian-doc/manpages/english/base-config/termwrap.8

.TH TERMWRAP 8
.SH NOMBRE
termwrap \- envuelve un terminal
.SH SINOPSIS
.B termwrap [-nnt] orden [args]
.SH DESCRIPCIÓN
.BR termwrap
se usa para ejecutar
.BR base-config (8)
en sistemas Debian recién instalados. Examina el entorno, toma nota de la
configuración de las opciones de localización y de que tipo de terminal está
disponible, para luego ejecutar un programa de terminal apropiado. Por ejemplo,
en una consola de Linux con configuración de localización japonesa ejecutará
jfterm. La orden especificada se ejecuta dentro del programa de terminal (si hay
alguno).
.SH OPCIONES
.TP
.I "-nnt"
No ejecutar otro terminal.
.SH TRADUCTOR
Traducción de Rubén Porras Campo <debian-l10n-spanish@lists.debian.org>
