.\" Translation of tzsetup.8 CVS revision 1.3
.\" Copyright 1998 Marcus Brinkmann (brinkmd@debian.org) (GPL)
.\" Polskie t³umaczenie Copyright 2001 Marcin Owsiany <porridge@debian.org>
.TH TZSETUP 8 "11 czerwca 2001" "Debian" "Konfiguracja strefy czasowej w Debianie"
.SH NAZWA
tzsetup \- ustaw lokan± strefê czasow±
.SH SK£ADNIA
.B tzsetup [-y] [-g]
.SH OPIS
Ta strona podrêcznika wyja¶nia jak mo¿na ustawiæ lokaln± strefê czasow±
przy pomocy narzêdzia
.BR tzsetup .
System operacyjny powinien znaæ ró¿nicê miêdzy czasem systemowym a lokalnym
(czasem w rzeczywistym ¶wiecie). Nalezy te¿ tak skonfigurowaæ system operacyjny,
aby zachowywa³ siê dobrze w czasie zmiany czasu z zimowego na letni i odwrotnie.

Prawid³owy czas systemowy oraz w³a¶ciwa lokalna strefa czasowa umo¿liwiaj±
to najlepiej. Jest to wa¿ne zw³aszcza w ¶rodowisku sieciowym, gdzie nawet
ma³e ró¿nice miêdzy czasami poszczególnych systemów mog± sprawiæ, ¿e na przyk³ad
serwer lustrzany niepotrzebnie pobierze ca³y serwis FTP, lub gdzie
wykorzystywane s± czasy modyfikacji plików w zdalnych systemach.
.\" FIXME: "where timestamps on external filesystems are used.

.B tzsetup
zazwyczas uruchamia siê z pow³oki bez ¿adnych parametrów. Mo¿na u¿yæ parametru
-y, dziêki czemu program nie bêdzie na pocz±tku pyta³ czy zmieniæ strefê
czasow±. Parametr -g s³u¿y do wymuszenia pytania o to, czy zegar
sprzêtowy jest ustawiony na ¶redni czas zachodnioeuropejski (GMT).

Po wybraniu strefy
.B tzsetup
spróbuje j± zmieniæ w systemie. Rozdzia³ 
.B Dzia³anie
zawiera szczegó³y techniczne tego procesu. Aby rzeczywi¶cie co¶ zmieniæ,
konieczne jest uruchomienie
.B tzsetup
z uprawnieniami nadzorcy. Aby tylko przejrzeæ strefy czasowe jako
zwyk³y u¿ytkownik, prosimy u¿ywaæ programu
.BR tzselect (1).
Wy¶wietli on czas lokalny w dowolnej strefie czasowej znanej systemowi.
.SH "OSTRZE¯ENIE"
Która strefa czasowa jest w³a¶ciwa dla Twojego systemu? Zale¿y to od
geograficznej lokalizacji maszyny. Ustawienie poprawnej lokalizacji jest wa¿ne,
ale system musi te¿ wiedzieæ, jak jest ustawiony zegar sprzêtowy.
Wiêkszo¶æ PC-tów ma zegar sprzêtowy ustawiony na czas lokalny, podczas gdy
wiêkszo¶æ systemów typu UNIX ustawia zegar sprzêtowy na czas uniwersalny (UTC).

System Debian GNU/Linux pobiera t± informacjê z pliku 
.IR /etc/default/rcS .
Zawiera on albo liniê
.BR UTC=yes , 
która oznacza, ¿e zegar sprzêtowy jest ustawiony na czas uniwersalny, lub liniê
.BR UTC=no ,
która oznacza, ¿e zegar sprzêtowy wskazuje czas lokalny. Je¶li ustawienie to
jest prawid³owe, to wybranie odpowiedniej systemowej strefy czasowej zapewni
wy¶wietlanie prawid³owej daty i czasu. Je¶li ustawienia te s± b³êdne, to 
wy¶wietlany czas bêdzie znacznie odbiega³ od rzeczywistego. Wiêcej
szczegó³ów na ten temat mo¿na znale¼æ w podrêczniku do programu
.BR hwclock (8).

.SH Dzia³anie
Dzia³anie programu
.B tzsetup
jest w rzeczywisto¶ci bardzo proste. Polega ono na aktualizacji
dowi±zania
.I /etc/localtime
aby wskazywa³o na odpowiedni± strefê czasow± zainstalowan± w katalogu
.IR /usr/share/zoneinfo/ .

Mo¿na to zrobiæ rêcznie, ale u¿ywaj±c programu 
.B tzsetup
nie trzeba pamiêtaæ ¶cie¿ki do stref czasowych.
.SH PLIKI
.I /etc/timezone
.BR
.I /etc/localtime
.BR
.I /usr/share/zoneinfo
.\" XXX:
.SH "POCHODZENIE"
Ten program jest oparty na programie
.BR tzconfig (8)
-- jedyna powa¿na ró¿nica to ta, ¿e ten program u¿ywa jako interfejsu
u¿ytkownika systemu debconf, i ¿e pozwala na konfiguracjê ¶redniego czasu
zachodnioeuropejskiego (GMT).
.SH "PATRZ TE¯"
.BR hwclock (8)
.BR tzselect (1)
.BR rcS (5)
.BR tzconfig (8)
.SH AUTOR
Joey Hess <joeyh@debian.org>
