#!/bin/sh
# Get the image, putting in the rigth place and mount it

PREREQ="network"

prereqs()
{
	echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
	prereqs
	exit 0
	;;
esac

# Just to be sure
modprobe -q squashfs
modprobe -q loop

IMAGE=${rootmnt}/image
mkdir -p ${IMAGE}

mount -o loop -t squashfs /mnt/META/META.squashfs $IMAGE
