#!/bin/sh
# Password setup is done by the passwd package.
set -e

if [ "$1" = new ]; then
	if [ -z "$DEBIAN_HAS_FRONTEND" ]; then
		dpkg-reconfigure --unseen-only --default-priority passwd
	fi
else
	exec dpkg-reconfigure --default-priority passwd
fi
