#!/bin/sh -e

. /usr/share/debconf/confmodule

ARCH=`udpkg --print-architecture`

log() {
    logger -t uda-pregrub-message "info: $@"
}

db_input critical uda-pregrub-message/pregrub-message || [ $? -eq 30 ]
db_go

log "Showing UDA pregrub message"

exit 0
