#!/bin/bash
# $Id: stopadsl,v 1.6 2005/01/16 22:08:17 Tux Exp $

# Copyright (C) 2003-2005 Olivier Borowski
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# Goal :
#	stop ADSL connexion
# Params :
#	h = display help
#	f = kill pppd even if PPPOX="none"
#	s = simple mode (don't use ifup & ifdown scripts => do not requiere ifcfg-ethX)

# the following line will be replaced by the absolute path of setvars
exit 123

# remove lock file (used by testconnec)
rm -f $SYSCONF_FILE

# terminate connexion
fctStopAdsl "$@"

#***************************************************************************
# $Log: stopadsl,v $
# Revision 1.6  2005/01/16 22:08:17  Tux
# - add license header
#
# Revision 1.5  2004/07/19 20:45:32  Tux
# - stopadsl now remove lock file (prevent testconnec to restart connection)
#
# Revision 1.4  2004/07/16 21:09:47  Tux
# - simplify parameters processing
#
# Revision 1.3  2004/04/21 20:02:27  Tux
# *** empty log message ***
#
#***************************************************************************/
