#!/bin/sh
# Run various programs to select packages to install.
set -e

case "$1" in
''|new)
	# Make dpkg not background itself to get a shell.
	export DPKG_NO_TSTP="yes"

	# scrollkeeper takes forever, so we divert it for the duration.
	dpkg-divert --package base-config --rename --quiet --add \
		/usr/bin/scrollkeeper-update
	dpkg-divert --package base-config --rename --quiet --add \
		/usr/bin/scrollkeeper-rebuilddb
	ln -sf /bin/true /usr/bin/scrollkeeper-update
	ln -sf /bin/true /usr/bin/scrollkeeper-rebuilddb
	touch /usr/lib/base-config/installing

	dpkg-reconfigure -phigh xserver-xorg

        /usr/bin/X11/X :8 -dpms -br -s 120 -dpi 100 -nolisten tcp &
        export DISPLAY=:8
		
        PACKAGES="gedit language-pack-en language-support-en"
        NUM_PACKAGES=$(apt-get install -s $PACKAGES | grep ^Inst | nl | tail -n 1 | cut -f1 | sed -e "s/ //g")
				
        sleep 5
        /usr/bin/metacity &
        sleep 9
							
        /usr/bin/uda-postinstall $NUM_PACKAGES "$PACKAGES"
	
	# Move final sources.list into place, if necessary, so that language
	# packs that aren't on the CD can be installed.
	if [ -f /etc/apt/sources.list.apt-setup ]; then
		db_progress INFO base-config/progress/prep
		mv -f /etc/apt/sources.list.apt-setup /etc/apt/sources.list
		apt-get -o Acquire::gpgv::Options::=--ignore-time-conflict update || true
	fi

	mkdir -p /var/lib/uda-postconfig
        chmod 700 /var/lib/uda-postconfig

        /usr/bin/uda-postconfig > /var/lib/uda-postconfig/post-config-info
        bash /usr/share/uda-postinstall/backend/uda-postconfig-backend.sh        rm -fr /var/lib/uda-postconfig
        rm /usr/lib/base-config/installing
	/usr/bin/uda-goodbye
        apt-get clean
        killall -9 Xorg

	;;
esac
